#-------------------------------------------------------------
# Manifest File to create Simple Deployment with Labels
#
# Copyleft (c) by Denis Astahov 2020
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      project: kgb
  template:
    metadata:
      labels:
        project: kgb
    spec:
      containers:
        - name : kgb-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80
